version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  release:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: 
                name: add github info
                command: |
                  git config user.email hi@sihuiliang.com
                  git config user.name circleCI@seeliang
            - run: 
                name: release package
                command: yarn && yarn release
workflows:
    release-package:
      jobs:
        - release:
            filters:
              branches:
                only:
                  - master
                  - merge-release