# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ github-action ]
  pull_request:
    branches: [ github-action ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: checkout 
      uses: actions/checkout@v2
    - name: Install Yarn
      run: npm install -g yarn
    - name: add info
      env: 
        GH_PACKAGE_TOKEN: ${{secrets.GH_PACKAGE_TOKEN}}
      run: |
        bash bash/publish_set.sh
    - name: Get remote branches
      run: |
        git remote set-branches origin '*'
        git fetch
    - name: yarn install 
      run: yarn install
    - name: yarn release 
      run: | 
        bash bash/release.sh
